backend:
  name: github
  repo: cnk/cnk.github.io
  branch: master
  site_domain: focused-lalande-aa3503.netlify.com

media_folder: "images/uploads"

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "_projects/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Image", name: "imagee", widget: "file"}
      - {label: "Image Alt Text", name: "alt", widget: "string"}
      - {label: "Looking", name: "looking", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Partner", name: "partner", widget: "string"}
      - {label: "Status", name: "status", widget: "string"}
      
